### ISSUE TITLE
can't install the module

### ISSUE THREAD

**Issue by DiDavid** [nkl-kst/MMM-OnThisDay#10]
When I try to install the module with "npm install --only=prod" it doesn't work and give my this error:
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/qs: Integrity verification failed for sha512-3WHAVfq77/5kmMX4o+i3vEm18OuE6LAQnm/EQA1sqZYhzx5VXZwNIXR6G5ZZf8rWMkdfY8aC3izK4QiN098u0A== (/home/pi/.npm/_cacache/content-v2/sha512/dd/61/c055fabbeffe6498c5f8a3e8b7bc49b5f0eb84e8b0109e6fc4400d6ca99621cf1e555d9c0d21747a1b96597fcad632475f63c682de2ccae1088dd3df2ed0)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-09-29T18_44_58_634Z-debug.log

**Comment by nkl-kst** [comment]
I don't think the registry errors are related to this module. However, you could try to run `npm cache verify` or `npm cache clean` and then install the module dependencies again.

-------- Ursprüngliche Nachricht --------Von: DiDavid <notifications@github.com> Datum: 29.09.20  20:46  (GMT+01:00) An: nkl-kst/MMM-OnThisDay <MMM-OnThisDay@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: [nkl-kst/MMM-OnThisDay] can't install the module (#10) 
When I try to install the module with "npm install --only=prod" it doesn't work and give my this error:
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see request/request#3142
npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/qs: Integrity verification failed for sha512-3WHAVfq77/5kmMX4o+i3vEm18OuE6LAQnm/EQA1sqZYhzx5VXZwNIXR6G5ZZf8rWMkdfY8aC3izK4QiN098u0A== (/home/pi/.npm/_cacache/content-v2/sha512/dd/61/c055fabbeffe6498c5f8a3e8b7bc49b5f0eb84e8b0109e6fc4400d6ca99621cf1e555d9c0d21747a1b96597fcad632475f63c682de2ccae1088dd3df2ed0)
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-09-29T18_44_58_634Z-debug.log
