### ISSUE TITLE
Use Wikimedia API Portal

### ISSUE THREAD

**Issue by nkl-kst** [nkl-kst/MMM-OnThisDay#26]
Data is available in a clean JSON repersenation under [Wikimedia API Portal](https://api.wikimedia.org/wiki/API_reference/Feed/On_this_day) ([Example](https://api.wikimedia.org/feed/v1/wikipedia/en/onthisday/all/03/28)). Using this API it is possible to solve issue #9 and add additional features like sorting events ascending/descending by year and show births/deaths.

**Comment by MarketingPip** [comment]
@nkl-kst - just found this by accident but! Hoping this helps you out! 

Check this library out! [OnThisDay.js](https://github.com/MarketingPipeline/OnThisDay.js)

In the process of adding features for different languages. (Which you can easily add a config to parse a certain Wiki)

Hopefully you can possibly contribute to it as well! 🤞 

Cheers!

**Comment by nkl-kst** [comment]
@MarketingPip Thanks for your hint. I saw that your library is some kind of a wrapper around https://www.npmjs.com/package/wtf_wikipedia for date specific fetches. For this module it's mandatory to get results for different languages and if I understand it correctly, there is currently no way to do it with your library.

Please let me know when this feature arrives in your libaray. Thanks again for opening this issue 👏

**Comment by MarketingPip** [comment]
@nkl-kst I have a fork started (still work in progress - since it's hard to add support for all Wikipedia languages as in various languages - some pages lead to another for Events, Births etc.. 

Tho if any interest on helping add support / finish the fork I have open. You're more than welcome / more than appreciated for anyone to jump on board! That said I'll still try to keep you updated when I have it finished with support for all languages. (Tho I do think I got the languages you have - all covered so far)

**Comment by slugmuffin** [comment]
@nkl-kst and @MarketingPip I made a new module for "OnThisDay" that uses the Wikimedia API. It can display similarly to this module or more like the newsfeed.

https://github.com/slugmuffin/MMM-OnThisDayWikiApi

**Comment by MarketingPip** [comment]
@slugmuffin - you should possible consider looking at my library & contributing so we add support for ALL language codes. As my library currently get's the results you need.....

**Comment by slugmuffin** [comment]
> @slugmuffin - you should possible consider looking at my library & contributing so we add support for ALL language codes. Then you can also make your library a plugin for this ie's nkl-ksts code...
> 

@MarketingPip - I'm pretty sure it supports all languages supported by the Wikimedia API. What other languages are you looking for?

@nkl-kst - I had considered forking this project, but I ended up different enough it didn't seem worth it. I do call it out with a "Thanks" though.

**Comment by MarketingPip** [comment]
@slugmuffin - personally I do not have a SmartMirror etc. So really (I could care less), but that said. Tho I do care about code etc / good open source work... lol 

It does appear your repo - is pretty well a spitting image of @nkl-kst's original library. Just with some various / smalll changes!

I personally would have forked his repo and make your pushes with your updates. As it will help keep the module active, rather than you guys all working separately to solve the same problem. (But again - that is just my two cent's).

**Comment by slugmuffin** [comment]
@MarketingPip - Sorry, as you seemed active on this topic, I assumed you had a "MagicMirror".

I did consider starting with a fork.  Much this project is dependent on how it gets its data and it seemed like it wanted to stick with the web scraping rather than the Wikipedia API. Although the projects are structured the same, a lot of the modules are. The code is closer to the built-in newsfeed  module. After I got the main code working, I actually came back to allow it to style similar to this module.
If @nkl-kst would like to, we can merge the projects.

**Comment by MarketingPip** [comment]
@nkl-kst - no worries! I am actually going to be stealing your idea / nkl-kst's idea to update my OnThisDay library (for browser / node.js etc) - which you can use anywhere. But I was using a package to scrape the packages which doesn't provide proper language support unless doing some gross scraping like you said. (I thought this repo / this issue - implied he added support via the API and not via scraping the HTML). 

That said - if I were him I would probably love that PR with your changes hahaha! And tbh - I will probably end up sneaking some ideas / end points out of your repo for my JavaScript library (which - maybe you want to contribute to) then you guys could possibly use that as import and use it here as well. 

See [here](https://github.com/MarketingPipeline/OnThisDay.js) if interested! 

Tho would be ideal to have a package / possibly sniff out other end points like this were we could make some nice libraries which could be used as imports so anyone can use them. (including MagicMirror users - like yourselves). 

ps; don't ask me how I jumped into this repo - just stumbled upon it while back and figured my library might have been helpful!
